=== agentsoz/ees-server/scripts/output/xsd/ees.xsd
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://github.com/agentsoz/bdi-abm-integration"
  xmlns="https://github.com/agentsoz/bdi-abm-integration"
  attributeFormDefault="unqualified"
  elementFormDefault="qualified">

  <xs:element name="opt">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="id"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="model">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="opt" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="id"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="global">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="opt" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="models">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="model" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="simulation">
    <xs:complexType>
      <xs:all>
        <xs:element ref="global" maxOccurs="1" minOccurs="0" />
        <xs:element ref="models" maxOccurs="1" minOccurs="0" />
      </xs:all>
      <xs:attribute type="xs:string" name="version"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== agentsoz/ees-server/scripts/output/surf-coast-shire/test/ees.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--===========================================================================
  #%L
  BDI-ABM Integration Package
  %%
  Copyright (C) 2014 - 2016 by its authors. See AUTHORS file.
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Lesser Public License for more details.

  You should have received a copy of the GNU General Lesser Public
  License along with this program.  If not, see
  <http://www.gnu.org/licenses/lgpl-3.0.html>.
  #L%
============================================================================-->

<simulation
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="https://github.com/agentsoz/bdi-abm-integration"
  xsi:schemaLocation="https://github.com/agentsoz/bdi-abm-integration ../../xsd/ees.xsd"
  version="v2.0">

  <!-- global configuration sent to all models -->
  <global>
    <!-- random seed to be used for all models; set to -1 if not used -->
    <opt id="randomSeed">1234</opt>
    <!-- coordinate reference system in EPSG format to be used for all models; see http://spatialreference.org -->
    <opt id="crs">EPSG:28355</opt>
    <!-- simulation start time in HH:MM format -->
    <opt id="startHHMM">00:00</opt>
  </global>

  <!-- model specific configuration -->
  <models>

    <model id="bdi">
      <!-- Jill BDI engine configuration arguments; DO NOT CHANGE IF UNSURE -->
      <opt id="jPlanSelectionPolicy">FIRST</opt>
      <opt id="jAgents"></opt>
      <opt id="jLogLevel">WARN</opt>
      <opt id="jLogFile">../../ees-data/test/output/io/github/agentsoz/ees/TypicalSummerWeekday50kTest/testTypicalSummerWeekday50k/jill.log</opt>
      <opt id="jOutFile">../../ees-data/test/output/io/github/agentsoz/ees/TypicalSummerWeekday50kTest/testTypicalSummerWeekday50k/jill.out</opt>
      <!--<opt id="jNumThreads">1</opt>-->
    </model>

    <model id="matsim">
      <!-- MATSim output directory relative to examples/bushfire directory (will overrule the setting in MATSim config) -->
      <opt id="outputDir">../../ees-data/test/output/io/github/agentsoz/ees/TypicalSummerWeekday50kTest/testTypicalSummerWeekday50k/matsim</opt>
      <!-- MATSim XML config XML file relative to examples/bushfire directory -->
      <opt id="configXml">../../ees-data/scenarios/surf-coast-shire/typical-summer-weekday-50k/scenario_matsim_main.xml</opt>
      <!-- Maximum distance at which the fire can be seen (in metres)-->
      <opt id="maxDistanceForFireVisual">1000</opt>
      <!-- Maximum distance at which smoke can be seen (in metres)-->
      <opt id="maxDistanceForSmokeVisual">5000</opt>
      <!-- Fire avoidance buffer used for planning routes for regular vehicles (in metres)-->
      <opt id="fireAvoidanceBufferForVehicles">5000</opt>
      <!-- Fire avoidance buffer used for planning routes for emergency vehicles (in metres)-->
      <opt id="fireAvoidanceBufferForEmergencyVehicles">1000</opt>
      <!-- Congestion parameters used by vehicles to decide if they are stuck in congestion. See issues
           https://github.com/agentsoz/bdi-abm-integration/issues/8 and
           https://github.com/agentsoz/bdi-abm-integration/issues/35 -->
      <opt id="congestionEvaluationInterval">180</opt>
      <opt id="congestionToleranceThreshold">0.33</opt>
      <opt id="congestionReactionProbability">0.0</opt> <!-- disable congestion replanning -->
    </model>

    <model id="phoenix">
      <!-- Phoenix start time in HH:MM format; used to calculate absolute values for hour_spot and hour_burnt -->
      <opt id="ignitionHHMM">00:00</opt>
      <!-- Phoenix fire GeoJSON file -->
      <opt id="fireGeoJson">../../ees-data/scenarios/surf-coast-shire/typical-summer-weekday-50k/scenario_fire.json</opt>
      <!-- Phoenix smoke (embers) GeoJSON file -->
      <opt id="smokeGeoJson"></opt>
    </model>

    <model id="disruption">
      <!-- Disruptions JSON file relative to examples/bushfire directory -->
      <opt id="fileJson"></opt>
    </model>

    <model id="messaging">
      <!-- Messaging JSON file  -->
      <opt id="fileJson"></opt>
      <!-- Zones GeoJSON file mapping zone IDs to polygon shapes -->
      <opt id="fileZonesGeoJson"></opt>
    </model>

  </models>

</simulation>

=== agentsoz/ees-server/scripts/templates/t_ees.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--===========================================================================
  #%L
  BDI-ABM Integration Package
  %%
  Copyright (C) 2014 - 2016 by its authors. See AUTHORS file.
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Lesser Public License for more details.

  You should have received a copy of the GNU General Lesser Public
  License along with this program.  If not, see
  <http://www.gnu.org/licenses/lgpl-3.0.html>.
  #L%
============================================================================-->

<simulation
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="https://github.com/agentsoz/bdi-abm-integration"
  xsi:schemaLocation="https://github.com/agentsoz/bdi-abm-integration ../../xsd/ees.xsd"
  version="v2.0">

  <!-- global configuration sent to all models -->
  <global>
    <!-- random seed to be used for all models; set to -1 if not used -->
    <opt id="randomSeed">${randomSeed}</opt>
    <!-- coordinate reference system in EPSG format to be used for all models; see http://spatialreference.org -->
    <opt id="crs">${crs}</opt>
    <!-- simulation start time in HH:MM format -->
    <opt id="startHHMM">${startHHMM}</opt>
  </global>

  <!-- model specific configuration -->
  <models>

    <model id="bdi">
      <!-- Jill BDI engine configuration arguments; DO NOT CHANGE IF UNSURE -->
      <opt id="jPlanSelectionPolicy">${jPlanSelectionPolicy}</opt>
      <opt id="jAgents"></opt>
      <opt id="jLogLevel">${jLogLevel}</opt>
      <opt id="jLogFile">${jLogFile}</opt>
      <opt id="jOutFile">${jOutFile}</opt>
      <!--<opt id="jNumThreads">1</opt>-->
    </model>

    <model id="matsim">
      <!-- MATSim output directory relative to examples/bushfire directory (will overrule the setting in MATSim config) -->
      <opt id="outputDir">${outputDir}</opt>
      <!-- MATSim XML config XML file relative to examples/bushfire directory -->
      <opt id="configXml">${configXml}</opt>
      <!-- Maximum distance at which the fire can be seen (in metres)-->
      <opt id="maxDistanceForFireVisual">${maxDistanceForFireVisual}</opt>
      <!-- Maximum distance at which smoke can be seen (in metres)-->
      <opt id="maxDistanceForSmokeVisual">${maxDistanceForSmokeVisual}</opt>
      <!-- Fire avoidance buffer used for planning routes for regular vehicles (in metres)-->
      <opt id="fireAvoidanceBufferForVehicles">${fireAvoidanceBufferForVehicles}</opt>
      <!-- Fire avoidance buffer used for planning routes for emergency vehicles (in metres)-->
      <opt id="fireAvoidanceBufferForEmergencyVehicles">${fireAvoidanceBufferForEmergencyVehicles}</opt>
      <!-- Congestion parameters used by vehicles to decide if they are stuck in congestion. See issues
           https://github.com/agentsoz/bdi-abm-integration/issues/8 and
           https://github.com/agentsoz/bdi-abm-integration/issues/35 -->
      <opt id="congestionEvaluationInterval">${congestionEvaluationInterval}</opt>
      <opt id="congestionToleranceThreshold">${congestionToleranceThreshold}</opt>
      <opt id="congestionReactionProbability">${congestionReactionProbability}</opt> <!-- disable congestion replanning -->
    </model>

    <model id="phoenix">
      <!-- Phoenix start time in HH:MM format; used to calculate absolute values for hour_spot and hour_burnt -->
      <opt id="ignitionHHMM">${ignitionHHMM}</opt>
      <!-- Phoenix fire GeoJSON file -->
      <opt id="fireGeoJson">${fireGeoJson}</opt>
      <!-- Phoenix smoke (embers) GeoJSON file -->
      <opt id="smokeGeoJson"></opt>
    </model>

    <model id="disruption">
      <!-- Disruptions JSON file relative to examples/bushfire directory -->
      <opt id="fileJson"></opt>
    </model>

    <model id="messaging">
      <!-- Messaging JSON file  -->
      <opt id="fileJson"></opt>
      <!-- Zones GeoJSON file mapping zone IDs to polygon shapes -->
      <opt id="fileZonesGeoJson"></opt>
    </model>

  </models>

</simulation>
