=== agentsoz/ees-server/scripts/output/xsd/main.xsd
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://github.com/agentsoz/bdi-abm-integration"
  xmlns="https://github.com/agentsoz/bdi-abm-integration"
  attributeFormDefault="unqualified"
  elementFormDefault="qualified">

  <!-- simple elements -->
  <xs:element name="name" type="xs:string"/>
  <xs:element name="coordinates" type="xs:string"/>
  <xs:element name="format" type="xs:string"/>
  <xs:element name="proportion" type="xs:string"/>
  <xs:element name="radiusInMtrs" type="xs:string"/>
  <xs:element name="start" type="xs:string"/>
  <xs:element name="peak" type="xs:string"/>

  <!-- complex elements -->

  <xs:element name="matsimfile" type="xs:string"/>

  <xs:element name="preEvacDetour">
    <xs:complexType>
      <xs:all>
        <xs:element ref="proportion"/>
        <xs:element ref="radiusInMtrs"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:element name="firefile">
    <xs:complexType>
      <xs:all>
        <xs:element ref="name"/>
        <xs:element ref="coordinates"/>
        <xs:element ref="format"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:element name="geographyfile">
    <xs:complexType>
      <xs:all>
        <xs:element ref="name"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:element name="trafficBehaviour">
    <xs:complexType>
      <xs:all>
        <xs:element ref="preEvacDetour"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:element name="evacuationTiming">
    <xs:complexType>
      <xs:all>
        <xs:element ref="start"/>
        <xs:element ref="peak"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:element name="bdiagents" type="xs:string"/>

  <!-- main structure -->
  <xs:element name="simulation">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="matsimfile">
        </xs:element>
        <xs:element ref="firefile">
        </xs:element>
        <xs:element ref="geographyfile">
        </xs:element>
        <xs:element ref="trafficBehaviour">
        </xs:element>
        <xs:element ref="evacuationTiming">
        </xs:element>
        <xs:element ref="bdiagents">
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== agentsoz/ees-server/scripts/output/test/scenario_main.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--===========================================================================
  #%L
  BDI-ABM Integration Package
  %%
  Copyright (C) 2014 - 2016 by its authors. See AUTHORS file.
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Lesser Public License for more details.

  You should have received a copy of the GNU General Lesser Public
  License along with this program.  If not, see
  <http://www.gnu.org/licenses/lgpl-3.0.html>.
  #L%
============================================================================-->


<!--===========================================================================
This is the top level config file for the scenario.
Its primary role is to point to all of the other config
and input files required by the scenario.
============================================================================-->

<simulation
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="https://github.com/agentsoz/bdi-abm-integration"
  xsi:schemaLocation="https://github.com/agentsoz/bdi-abm-integration ../../xsd/main.xsd">

<!--===========================================================================
Specifies the top level MATSim configuration file for this scenario
  name:
    path to file; if using relative path, specify relative to the
    bushfire root directory, e.g., ./sample_data/maldon.xml
============================================================================-->
<matsimfile>scenarios/surf-coast-shire/typical-summer-weekday-50k/scenario_matsim_main.xml</matsimfile>

<!--===========================================================================
Specifies the timestamped fire progression fire model file

  name:
    path to fire model file; if using relative path, specify relative to the
    bushfire root directory, e.g., scenarios/maldon-simple/maldon_fire.xml

  coordinates:
    coordinate system used in the input file; should be one of {utm,latlong}

  format:
    fire file format; should be one of {geojson}

For an example of the fire input file see ./sample_data/maldon_fire.json
============================================================================-->
<firefile>
  <name></name>
  <coordinates>latlong</coordinates>
  <format>geojson</format>
</firefile>

<!--===========================================================================
Specifies the geography file for this scenario

  name:
    path to file; if using relative path, specify relative to the
    bushfire root directory, e.g., scenarios/maldon-simple/maldon_geography.xml

  coordinates:
    coordinate system used in the input file; should be one of {utm,latlong}

For an example of the geography file see ./sample_data/maldon_geography.json
============================================================================-->
<geographyfile>
  <name>scenarios/surf-coast-shire/typical-summer-weekday-50k/scenario_geography.xml</name>
</geographyfile>

<!--===========================================================================
Specify attributes that impact the behaviour of vehicles during evacuation

  relatives:
    the proportion of vehicles (between 0.0-1.0) that will first take a detour
    to a nearby location (determined by the max_distance_to_relatives value)
    to attend to loved ones (relatives), before evacuating towards the
    designated relief centres.

  max_distance_to_relatives:
    the maximum distance (in mtrs) from an agent's start location to the detour
    location; for example setting this to 1000 will force vehicles that detour
    to check on relatives to drive up to 1km to an arbitrarily chosen location
    prior to evacuating.

============================================================================-->
<trafficBehaviour> <!-- NOT USED -->
  <preEvacDetour>
    <proportion>0.0</proportion>
    <radiusInMtrs>0</radiusInMtrs>
  </preEvacDetour>
</trafficBehaviour>

<!--===========================================================================
Specify the timing of the evacuation

  evac_start:
     time of day in HH:MM when the evacuation should start
  evac_peak:
     time in MINS past the evacuation start time at which the peak of
     vehicles leaving will occur; in other words, evac_start defines the
     left tail extreme of a normal distribution that has a mean at evac_peak.

============================================================================-->
<evacuationTiming>
  <start>00:00</start>
  <peak>00</peak>
</evacuationTiming>


<!--===========================================================================
Number of BDI agents (N) to initialise.

The total number of agents (M) is determined by the MATSim population file.

The final number of BDI agents will be the lesser of N,M. Setting N really high
(so that it is always greater than M), will ensure that the entire MATSim
population has BDI conterparts.
============================================================================-->
<bdiagents> <!-- NOT USED -->
bdiagents
</bdiagents>

<!--=========================================================================-->
</simulation>
